server:
    port: 8080
spring:
    application:
        name: pawshake-saga-reservation
---
spring:
    profiles: default
    jpa:
        generate-ddl: true
        properties:
            hibernate:
                show_sql: true
                format_sql: true

    datasource:
        url: jdbc:mysql://${DOCKER_HOST_IP:localhost}/eventuate
        username: mysqluser
        password: mysqlpw
        driver-class-name: com.mysql.cj.jdbc.Driver

eventuatelocal:
    kafka:
        bootstrap.servers: ${DOCKER_HOST_IP:localhost}:9092

cdc:
    service:
        url: http://localhost:8099

logging:
    level:
        org.hibernate.type: trace
        org.springframework.cloud: debug

server:
    port: 8084
